POST http://localhost:3001/authenticate
Content-Type: application/json

# { "username": "rama" }

{
    "username": "adam_la_morre",
    "first_name": "Adam",
    "last_name": "La Morre",
    "secret": "pass1234",
    "custom_json": {"high_score": 2000}
}